server:
  port: 8080


#datasource
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/t1?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    initialization-mode: always

#mybatis
mybatis:
  mapper-locations: classpath:com.iio.modules.user.mapper/*.xml
  #type-aliases-package:
  configuration:
    #mybatis 打印sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl